version: '3.8'

services:
  exo_companion_scraper:
    build:
      context: ./exo_companion_scraper
      dockerfile: Dockerfile
    networks:
      - exo_network

  exo_companion_api:
    build:
      context: ./exo_companion_api
      dockerfile: Dockerfile
    networks:
      - exo_network

  exo_companion_ui:
    build:
      context: ./exo_companion_ui
      dockerfile: Dockerfile
    networks:
      - exo_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: exo_database
      POSTGRES_USER: exo_user
      POSTGRES_PASSWORD: exo_password
    ports:
      - "5432:5432"
    networks:
      - exo_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - exo_network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    networks:
      - exo_network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - exo_network

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3001:3000"
    networks:
      - exo_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - exo_network

networks:
  exo_network:
    driver: bridge